name: Deploy-AZ-Func-PROD

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: conversion-trigger   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                 # set this to the Python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build-and-deploy-PROD:
    runs-on: [ self-hosted, small , warp ]
    environment: PROD
    steps:
      - name: 'Checkout GitHub action'
        uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          popd

      - name: Run unit tests
        run: |
          python -m unittest discover ./tests

      - name: 'Run Azure Functions action'
        uses: Azure/functions-action@v1.5.1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
